name: Build and Deploy JupyterLite

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyterlite-core jupyterlite-pyodide-kernel

      - name: Build JupyterLite
        run: |
          # JupyterLite expects files in a 'files' directory at the root
          mkdir -p files
          cp content/Elasticity_Tool.ipynb files/
          cp content/soda.csv files/

          # Build JupyterLite with the files directory as content
          jupyter lite build --files files --output-dir _output

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4